### ISSUE TITLE
セルの高さをLabelの内容に応じて可変にする

### ISSUE THREAD

**Issue by LittIe-ma** [LittIe-ma/customCell_by_xib#2]

**Comment by shinohara-san** [comment]
viewDidAppearで外から更新するよりもcellでサイズを計算したほうがよさそ

https://qiita.com/noppefoxwolf/items/7bee990c89d41d554c7d

**Comment by shinohara-san** [comment]
いろいろ見てたらcellのcontentViewとさらにその中のpostView、この二つがxibファイル編集画面でcontrol + dragで接続できずでした(なぜかはわからず。試しにpostViewを削除して新しくViewを追加したら接続できた)。なのでそこらへん怪しいなと思って、その新しく置いたViewの中に同じようなレイアウトでcellを作成してみたら可変にできたので、もしかしたら細かい制約の付け方で間違ってたのかもですね。参考にしたいというときはpermissionもらえればソースコードpushするのでその時は言ってください(結局話題に上がってたpriorityやgreater thanとかも使わずでした)

**Comment by LittIe-ma** [comment]
@shinohara-san 
お休みの日にありがとうございます！
なるほど、UI部品をコピペしたりしてたのでそれが問題だったり。
リポジトリのリンクを送ったのですが合ってますかね？
やり方間違ってたらご指摘ください。
